apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: jgreen
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/jgreen-harbor-project/db@sha256:a57f094a13c8dbfcfac205c69be86690f8d7def4eb8840fe693aa89509c277d9
        ports:
        - containerPort: 5432
